---
# molecule.yml — TDD cycle complet pour le rôle users.
dependency:
  name: galaxy

driver:
  name: default

platforms:
  - name: instance
    image: docker.io/rockylinux/rockylinux:9
    pre_build_image: true
    privileged: true
    command: /sbin/init

provisioner:
  name: ansible
  config_options:
    defaults:
      stdout_callback: yaml
      callback_enabled: profile_tasks

verifier:
  name: ansible
