---
# Inventaire enrichi pour démontrer les patterns d'hôtes.
# Réutilise les VMs du lab + 2 hôtes "factices" pour les patterns avancés.
all:
  vars:
    ansible_user: ansible
    ansible_ssh_private_key_file: "{{ inventory_dir }}/../../../ssh/id_ed25519"
    ansible_python_interpreter: /usr/bin/python3.12

  children:
    webservers:
      hosts:
        web1.lab:
          ansible_host: 10.10.20.21
        web2.lab:
          ansible_host: 10.10.20.22

    dbservers:
      hosts:
        db1.lab:
          ansible_host: 10.10.20.31

    prod:
      children:
        webservers:
        dbservers:

    staging:
      hosts:
        web1.lab:    # web1 fait partie de staging ET prod (pour les patterns d'intersection)

    monitoring:
      hosts:
        db1.lab:     # db1 est aussi dans monitoring (intersection avec dbservers)
