---
# execution-environment-buggy.yml : définition d'EE héritée d'un ancien
# projet. Le build « passe » ou échoue selon les cas, mais l'EE produit
# n'est pas utilisable. À vous de diagnostiquer pourquoi.

images:
  base_image:
    name: ghcr.io/ansible-community/community-ee-minimal:latest

dependencies:
  ansible_core:
    package_pip: ansible-core==2.18.1
  galaxy: requirements-buggy.yml
  python: requirements-buggy.txt
