---
# vars/Debian.yml : À COMPLÉTER PAR VOS SOINS.
# Variables spécifiques à la famille Debian/Ubuntu. Attention : le
# répertoire HTML et l'utilisateur nginx n'y sont pas les mêmes que sur
# RHEL, c'est tout l'objet du lab.
__webserver_package_name: ???
__webserver_service_name: ???
__webserver_html_dir: ???
__webserver_user: ???
